OLUYEMI OLUWOYE
assignment 4

## Task 1: Create a DataFrame

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
from functools import reduce

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco' , 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)
print("\nData Types:\n", df.dtypes)

Original DataFrame:
      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

Data Types:
 Name    object
Age      int64
City    object
dtype: object

# Task 2: Row and Column Manipulation

In [ ]:

df_dropped = df.drop(columns=['City'])
print("\nDataFrame after dropping 'City' column:")
print(df_dropped)

DataFrame after dropping 'City' column:
      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28

# Task 3: Handling Null Values

In [ ]:

df_nulls = pd.DataFrame({
    'A': [1, np.nan, 3],
    'B': [np.nan, 'hello', 'world'],
    'C': [np.nan, np.nan, np.nan]
})
print("\nDataFrame with Nulls:")
print(df_nulls)

# Fill NaNs
df_filled = df_nulls.fillna({
    'A': 0,
    'B': 'N/A',
    'C': 'Unknown'
})
print("\nDataFrame after filling Nulls:")
print(df_filled)

DataFrame with Nulls:
     A      B   C
0  1.0    NaN NaN
1  NaN  hello NaN
2  3.0  world NaN

DataFrame after filling Nulls:
     A      B        C
0  1.0    N/A  Unknown
1  0.0  hello  Unknown
2  3.0  world  Unknown

# Task 4: GroupBy and Describe

In [ ]:


group_data = pd.DataFrame({
      'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Value': [10, 20, 15, 25, 30, 35]
})

print("\nGroupBy and Describe:")
group_stats = group_data.groupby('Category')['Value'].describe()
print(group_stats)

GroupBy and Describe:
          count       mean        std   min    25%   50%    75%   max
Category
A           3.0  18.333333  10.408330  10.0  12.50  15.0  22.50  30.0
B           2.0  22.500000   3.535534  20.0  21.25  22.5  23.75  25.0
C           1.0  35.000000        NaN  35.0  35.00  35.0  35.00  35.0

In [ ]:
# Task 5: Concatenation and Merging

In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'C': [9, 10], 'D': [11, 12]})

concat_df = pd.concat([df1, df2], ignore_index=True)
merged_df = pd.concat([concat_df, df3], axis=1)
print("\nConcatenated and Merged DataFrame:")
print(merged_df)

Concatenated and Merged DataFrame:
   A  B     C     D
0  1  3   9.0  11.0
1  2  4  10.0  12.0
2  5  7   NaN   NaN
3  6  8   NaN   NaN

# Task 6: Tuples and Sets

In [ ]:

fruits = ('apple', 'banana', 'cherry')
numbers = {1, 2, 3, 4, 5}

try:
    fruits += ('orange',)  # Tuples are immutable, create a new one
    print("\nNew Tuple:", fruits)
except Exception as e:
    print("Tuple Error:", e)

numbers.add(6)
print("Set after adding 6:", numbers)

New Tuple: ('apple', 'banana', 'cherry', 'orange')
Set after adding 6: {1, 2, 3, 4, 5, 6}

# Task 7: Dictionaries

In [ ]:

students = {'Yemi': 85, 'Olu': 90, 'Akin': 78}
students['Yemi'] = 88            # Update score
students['David'] = 92            # Add new student
print("\nUpdated Dictionary of Students:")
print(students)

Updated Dictionary of Students:
{'Yemi': 88, 'Olu': 90, 'Akin': 78, 'David': 92}

# Task 8: Functions and Lambda

In [ ]:

def square(x):
    return x * x

square_lambda = lambda x: x * x

print("\nFunction Output:", square(4), square(9))
print("Lambda Output:", square_lambda(4), square_lambda(9))

Function Output: 16 81
Lambda Output: 16 81

# Task 9: Iterators and Generators

In [ ]:

class EvenIterator:
    def __init__(self):
        self.num = 0
        self.count = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.count >= 5:
            raise StopIteration
        self.num += 2
        self.count += 1
        return self.num

In [ ]:
def even_generator():
    num = 2
    for _ in range(5):
        yield num
        num += 2

print("\nEven Iterator:")
for num in EvenIterator():
    print(num, end=' ')

print("\nEven Generator:")
for num in even_generator():
    print(num, end=' ')

Even Iterator:
2 4 6 8 10
Even Generator:
2 4 6 8 10

# Task 10: Map, Reduce, Filter

In [ ]:

from functools import reduce

numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x**2, numbers))
product = reduce(lambda x, y: x * y, numbers)
evens = list(filter(lambda x: x % 2 == 0, numbers))

print("\n\nMap (Squared):", squared)
print("Reduce (Product):", product)
print("Filter (Evens):", evens)

Map (Squared): [1, 4, 9, 16, 25]
Reduce (Product): 120
Filter (Evens): [2, 4]

# Task 11: Object-Oriented Programming

In [ ]:

class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

r1 = Rectangle(5, 3)
r2 = Rectangle(7, 2)

print("\nRectangle 1 - Area:", r1.area(), ", Perimeter:", r1.perimeter())
print("Rectangle 2 - Area:", r2.area(), ", Perimeter:", r2.perimeter())

Rectangle 1 - Area: 15 , Perimeter: 16
Rectangle 2 - Area: 14 , Perimeter: 18

#Task 12: Pandas Data Analysis

In [ ]:

emp_data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'IT', 'Finance'],
    'Salary': [55000, 70000, 62000, 48000]
})

In [ ]:
# Average salary by department
avg_salary = emp_data.groupby('Department')['Salary'].mean()
print("\nAverage Salary by Department:")
print(avg_salary)

Average Salary by Department:
Department
Finance    48000.0
HR         55000.0
IT         66000.0
Name: Salary, dtype: float64

In [ ]:
# Employees with salary > 60000
high_earners = emp_data[emp_data['Salary'] > 60000]['Name']
print("\nEmployees with Salary > 60000:")
print(high_earners.tolist())

Employees with Salary > 60000:
['Bob', 'Charlie']

In [ ]:
# Add Bonus column (10%)
emp_data['Bonus'] = emp_data['Salary'] * 0.10
print("\nDataFrame with Bonus:")
print(emp_data)

DataFrame with Bonus:
      Name Department  Salary   Bonus
0    Alice         HR   55000  5500.0
1      Bob         IT   70000  7000.0
2  Charlie         IT   62000  6200.0
3    David    Finance   48000  4800.0

In [24]:
!git status

fatal: not a git repository (or any of the parent directories): .git

In [25]:
!git clone https://github.com/OLUYEMI84/cola-GITHUB-demo-OO.git
%cd cola-GITHUB-demo-OO
!ls

Cloning into 'cola-GITHUB-demo-OO'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 6 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (9/9), 387.85 KiB | 3.49 MiB/s, done.
/content/cola-GITHUB-demo-OO
assignment2.ipynb  Lesson_5_Assignment.ipynb  README.md

In [26]:
%ls

assignment2.ipynb  Lesson_5_Assignment.ipynb  README.md

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import shutil

source_path = '/content/drive/MyDrive/Colab Notebooks/Lesson_5_Assignment.ipynb'
destination_path = '/content/cola-GITHUB-demo-OO/Lesson_5_Assignment.ipynb'

shutil.copy(source_path, destination_path)